### ISSUE TITLE
WebApp Authentication

### ISSUE THREAD

**Issue by thijstakken** [thijstakken/MusicService#53]
Since all settings will be moved to a WebApp, they will be exposed.
There will be need for authentication, so your settings and app are protected. (login page)

**Comment by thijstakken** [comment]
- [ ] Should it be single user based or multi user support?
- [ ] Modularity needed?
- [ ] MFA?
- [ ] Passkeys?

Inspiration:
https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login

**Comment by thijstakken** [comment]
Investigated options for handling authentication.

1. Flask-Login (checks all criteria, basic and simple)
2. Flask-Security (more complex, contains features which are not needed now)
3. Flask-User (not needed)

Going to implement Flask-Login for the app.

**Comment by thijstakken** [comment]
going to use Flask-WTF for the forms, forms are better protected against various common attacks this way.

**Comment by thijstakken** [comment]
register has to be one time, only if no users exist, and then dissapear.

for later: an admin panel could be added, from where the first user (admin) could create new users, or allow new users to register themselfs. but this function should be disabled by default and one the admin should be able to enable it again.

**Comment by calonmerc** [comment]
Recommend env flag to disable security for explicitly internal application use.

**Comment by thijstakken** [comment]
With security, do you mean the whole authentication of users? @calonmerc

**Comment by thijstakken** [comment]
Yes I agree, I have the same more or less environment. I can see your case. What would be possible in the future is to add an "login bypass" for those who really want it.

When you have created your first user account (the app needs a user, all objects are tied to a user) you could probably set a toggle in the account settings to bypass authentication. This could be implemented for sure, it's possible to make such a flow. 

But probably somewhere in the future. I will first have to focus on getting a working MVP out.
